# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2

# this would enable querying all packages from our repo first,
# disabled for now as we do not want to use it. Kept for reference.
#registries:
#  openhab-jfrog:
#    type: "maven-repository"
#    url: "https://openhab.jfrog.io/artifactory/libs-all/"

updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - dependencies
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels: [ ]
    registries: "*"
    allow:
      - dependency-name: "*"
      - dependency-name: "org.openhab.core.tools:i18n-maven-plugin"
    ignore:
    # some manually generated entries, mostly plugins handled together with other upgrades
      - dependency-name: "com.diffplug.spotless:spotless-maven-plugin" # done with SAT
      - dependency-name: "org.eclipse.xtend:xtend-maven-plugin" # done with xtext/xtend
    # automatically generated list of all package dependencies - all shall be ignored for now
    #
    # to generate this list: bash
    # mvn dependency:tree |grep -v "from "|grep -e "[a-zA-Z\0-9-]\+\:[a-zA-Z\-]\+"|grep -v "dependency:.*:tree"|sed "s/\[[A-Z]*\][|\ +-]*//g"|sed "s/\[INFO\]//"|sed "s/:jar:.*//"|grep -v "The POM"|sort -u|grep -v openhab.core.|sed "s/^/      - dependency-name: \"/"|sed "s/$/\"/" >> .github/dependabot.yml
    #
      - dependency-name: "ch.qos.logback.contrib:logback-jackson"
      - dependency-name: "ch.qos.logback.contrib:logback-json-classic"
      - dependency-name: "ch.qos.logback.contrib:logback-json-core"
      - dependency-name: "ch.qos.logback:logback-classic"
      - dependency-name: "ch.qos.logback:logback-core"
      - dependency-name: "ch.qos.reload4j:reload4j"
      - dependency-name: "com.fasterxml.jackson.core:jackson-annotations"
      - dependency-name: "com.fasterxml.jackson.core:jackson-core"
      - dependency-name: "com.fasterxml.jackson.core:jackson-databind"
      - dependency-name: "com.fasterxml.woodstox:woodstox-core"
      - dependency-name: "com.jayway.jsonpath:json-path"
      - dependency-name: "com.madgag:animated-gif-lib"
      - dependency-name: "com.sun.activation:jakarta.activation"
      - dependency-name: "com.sun.istack:istack-commons-runtime"
      - dependency-name: "com.sun.xml.bind:jaxb-osgi"
      - dependency-name: "com.zsmartsystems.zigbee:com.zsmartsystems.zigbee"
      - dependency-name: "com.zsmartsystems.zigbee:com.zsmartsystems.zigbee.console"
      - dependency-name: "com.zsmartsystems.zigbee:com.zsmartsystems.zigbee.console.ember"
      - dependency-name: "com.zsmartsystems.zigbee:com.zsmartsystems.zigbee.console.telegesis"
      - dependency-name: "com.zsmartsystems.zigbee:com.zsmartsystems.zigbee.dongle.cc2531"
      - dependency-name: "com.zsmartsystems.zigbee:com.zsmartsystems.zigbee.dongle.ember"
      - dependency-name: "com.zsmartsystems.zigbee:com.zsmartsystems.zigbee.dongle.telegesis"
      - dependency-name: "com.zsmartsystems.zigbee:com.zsmartsystems.zigbee.dongle.xbee"
      - dependency-name: "commons-logging:commons-logging"
      - dependency-name: "commons-net:commons-net"
      - dependency-name: "de.erichseifert.vectorgraphics2d:VectorGraphics2D"
      - dependency-name: "de.rototor.pdfbox:graphics2d"
      - dependency-name: "io.dropwizard.metrics:metrics-core"
      - dependency-name: "io.micrometer:micrometer-commons"
      - dependency-name: "io.micrometer:micrometer-core"
      - dependency-name: "io.micrometer:micrometer-observation"
      - dependency-name: "jakarta.annotation:jakarta.annotation-api"
      - dependency-name: "jakarta.ws.rs:jakarta.ws.rs-api"
      - dependency-name: "jakarta.xml.bind:jakarta.xml.bind-api"
      - dependency-name: "javax.activation:activation"
      - dependency-name: "javax.annotation:javax.annotation-api"
      - dependency-name: "javazoom:jlayer"
      - dependency-name: "log4j:log4j"
      - dependency-name: "net.bytebuddy:byte-buddy"
      - dependency-name: "net.bytebuddy:byte-buddy-agent"
      - dependency-name: "net.java.dev.jna:jna"
      - dependency-name: "net.java.dev.jna:jna-platform"
      - dependency-name: "net.minidev:accessors-smart"
      - dependency-name: "net.minidev:json-smart"
      - dependency-name: "net.wimpi:jamod"
      - dependency-name: "org.apache.aries.component-dsl:org.apache.aries.component-dsl.component-dsl"
      - dependency-name: "org.apache.aries.jax.rs:org.apache.aries.jax.rs.whiteboard"
      - dependency-name: "org.apache.commons:commons-pool2"
      - dependency-name: "org.apache.cxf:cxf-core"
      - dependency-name: "org.apache.cxf:cxf-rt-frontend-jaxrs"
      - dependency-name: "org.apache.cxf:cxf-rt-rs-client"
      - dependency-name: "org.apache.cxf:cxf-rt-rs-sse"
      - dependency-name: "org.apache.cxf:cxf-rt-security"
      - dependency-name: "org.apache.cxf:cxf-rt-transports-http"
      - dependency-name: "org.apache.felix:org.apache.felix.cm.json"
      - dependency-name: "org.apache.felix:org.apache.felix.configadmin"
      - dependency-name: "org.apache.felix:org.apache.felix.configadmin.plugin.interpolation"
      - dependency-name: "org.apache.felix:org.apache.felix.fileinstall"
      - dependency-name: "org.apache.felix:org.apache.felix.framework"
      - dependency-name: "org.apache.felix:org.apache.felix.http.servlet-api"
      - dependency-name: "org.apache.felix:org.apache.felix.utils"
      - dependency-name: "org.apache.geronimo.specs:geronimo-jaxws_2.2_spec"
      - dependency-name: "org.apache.geronimo.specs:geronimo-json_1.1_spec"
      - dependency-name: "org.apache.geronimo.specs:geronimo-saaj_1.3_spec"
      - dependency-name: "org.apache.geronimo.specs:geronimo-stax-api_1.2_spec"
      - dependency-name: "org.apache.karaf.config:org.apache.karaf.config.core"
      - dependency-name: "org.apache.karaf.diagnostic:org.apache.karaf.diagnostic.boot"
      - dependency-name: "org.apache.karaf.features:base"
      - dependency-name: "org.apache.karaf.features:framework:kar:4.4.7:compile"
      - dependency-name: "org.apache.karaf.features:framework:kar:4.4.7:provided"
      - dependency-name: "org.apache.karaf.features:org.apache.karaf.features.core"
      - dependency-name: "org.apache.karaf.features:org.apache.karaf.features.extension"
      - dependency-name: "org.apache.karaf.features:specs:xml:features:4.4.7:compile"
      - dependency-name: "org.apache.karaf.features:standard:xml:features:4.4.7:compile"
      - dependency-name: "org.apache.karaf.jaas:org.apache.karaf.jaas.boot"
      - dependency-name: "org.apache.karaf.kar:org.apache.karaf.kar.core"
      - dependency-name: "org.apache.karaf.specs:org.apache.karaf.specs.activator"
      - dependency-name: "org.apache.karaf.specs:org.apache.karaf.specs.java.xml"
      - dependency-name: "org.apache.karaf.specs:org.apache.karaf.specs.java.xml.ws"
      - dependency-name: "org.apache.karaf.specs:org.apache.karaf.specs.locator"
      - dependency-name: "org.apache.karaf:org.apache.karaf.client"
      - dependency-name: "org.apache.karaf:org.apache.karaf.main"
      - dependency-name: "org.apache.karaf:org.apache.karaf.util"
      - dependency-name: "org.apache.logging.log4j:log4j-api"
      - dependency-name: "org.apache.logging.log4j:log4j-core"
      - dependency-name: "org.apache.pdfbox:fontbox"
      - dependency-name: "org.apache.pdfbox:pdfbox"
      - dependency-name: "org.apache.pdfbox:pdfbox-io"
      - dependency-name: "org.apache.servicemix.specs:org.apache.servicemix.specs.activation-api-1.2.1"
      - dependency-name: "org.apache.sling:org.apache.sling.commons.johnzon"
      - dependency-name: "org.apache.sshd:sshd-osgi"
      - dependency-name: "org.apache.ws.xmlschema:xmlschema-core"
      - dependency-name: "org.apiguardian:apiguardian-api"
      - dependency-name: "org.bouncycastle:bcpkix-jdk18on"
      - dependency-name: "org.bouncycastle:bcprov-jdk18on"
      - dependency-name: "org.bouncycastle:bcutil-jdk18on"
      - dependency-name: "org.codehaus.mojo:animal-sniffer-annotations"
      - dependency-name: "org.codehaus.woodstox:stax2-api"
      - dependency-name: "org.eclipse.jdt:org.eclipse.jdt.annotation"
      - dependency-name: "org.eclipse.platform:org.eclipse.osgi"
      - dependency-name: "org.glassfish.jaxb:jaxb-runtime"
      - dependency-name: "org.glassfish.jaxb:txw2"
      - dependency-name: "org.hamcrest:hamcrest"
      - dependency-name: "org.hdrhistogram:HdrHistogram"
      - dependency-name: "org.jline:jline"
      - dependency-name: "org.junit.jupiter:junit-jupiter-api"
      - dependency-name: "org.junit.jupiter:junit-jupiter-params"
      - dependency-name: "org.junit.platform:junit-platform-commons"
      - dependency-name: "org.knowm.xchart:xchart"
      - dependency-name: "org.latencyutils:LatencyUtils"
      - dependency-name: "org.mockito:mockito-core"
      - dependency-name: "org.mockito:mockito-junit-jupiter"
      - dependency-name: "org.objenesis:objenesis"
      - dependency-name: "org.openhab.addons.bundles:org.openhab.binding.zigbee"
      - dependency-name: "org.openhab.addons.bundles:org.openhab.binding.zigbee.cc2531"
      - dependency-name: "org.openhab.addons.bundles:org.openhab.binding.zigbee.console"
      - dependency-name: "org.openhab.addons.bundles:org.openhab.binding.zigbee.console.ember"
      - dependency-name: "org.openhab.addons.bundles:org.openhab.binding.zigbee.console.telegesis"
      - dependency-name: "org.openhab.addons.bundles:org.openhab.binding.zigbee.ember"
      - dependency-name: "org.openhab.addons.bundles:org.openhab.binding.zigbee.firmware"
      - dependency-name: "org.openhab.addons.bundles:org.openhab.binding.zigbee.serial"
      - dependency-name: "org.openhab.addons.bundles:org.openhab.binding.zigbee.slzb06"
      - dependency-name: "org.openhab.addons.bundles:org.openhab.binding.zigbee.telegesis"
      - dependency-name: "org.openhab.addons.bundles:org.openhab.binding.zigbee.xbee"
      - dependency-name: "org.openhab.addons.features.karaf:openhab-binding-zigbee:xml:features:5.0.0-SNAPSHOT:compile"
      - dependency-name: "org.openhab.addons.features.karaf:openhab-binding-zigbee:xml:features:5.0.0-SNAPSHOT:provided"
      - dependency-name: "org.openhab.addons.features.karaf:openhab-binding-zigbee:xml:features:5.0.0-SNAPSHOT:runtime"
      - dependency-name: "org.openhab.addons.features.karaf:org.openhab.addons.features.karaf.openhab-addons:xml:features:5.0.0-SNAPSHOT:compile"
      - dependency-name: "org.openhab.addons.features.karaf:org.openhab.addons.features.karaf.openhab-addons:xml:features:5.0.0-SNAPSHOT:provided"
      - dependency-name: "org.openhab.addons.features.karaf:org.openhab.addons.features.karaf.openhab-addons:xml:features:5.0.0-SNAPSHOT:runtime"
      - dependency-name: "org.openhab.distro:addons:feature:5.0.0-SNAPSHOT"
      - dependency-name: "org.openhab.distro:addons:xml:features:5.0.0-SNAPSHOT:compile"
      - dependency-name: "org.openhab.distro:addons:xml:features:5.0.0-SNAPSHOT:provided"
      - dependency-name: "org.openhab.distro:addons:xml:features:5.0.0-SNAPSHOT:runtime"
      - dependency-name: "org.openhab.distro:distro-kar:kar:5.0.0-SNAPSHOT"
      - dependency-name: "org.openhab.distro:distro-kar:kar:5.0.0-SNAPSHOT:provided"
      - dependency-name: "org.openhab.distro:distro:feature:5.0.0-SNAPSHOT"
      - dependency-name: "org.openhab.distro:distro:xml:features:5.0.0-SNAPSHOT:compile"
      - dependency-name: "org.openhab.distro:distro:xml:features:5.0.0-SNAPSHOT:provided"
      - dependency-name: "org.openhab.distro:distro:xml:features:5.0.0-SNAPSHOT:runtime"
      - dependency-name: "org.openhab.distro:openhab-addons:kar:5.0.0-SNAPSHOT"
      - dependency-name: "org.openhab.distro:openhab-addons:kar:5.0.0-SNAPSHOT:provided"
      - dependency-name: "org.openhab.distro:openhab-addons:xml:features:5.0.0-SNAPSHOT:runtime"
      - dependency-name: "org.openhab.distro:openhab-demo:pom:5.0.0-SNAPSHOT"
      - dependency-name: "org.openhab.distro:openhab-verify:pom:5.0.0-SNAPSHOT"
      - dependency-name: "org.openhab.distro:openhab:karaf-assembly:5.0.0-SNAPSHOT"
      - dependency-name: "org.openhab.distro:pom-distributions:pom:5.0.0-SNAPSHOT"
      - dependency-name: "org.openhab.distro:pom-features:pom:5.0.0-SNAPSHOT"
      - dependency-name: "org.openhab.distro:pom:pom:5.0.0-SNAPSHOT"
      - dependency-name: "org.openhab.ui.features:org.openhab.ui.features:xml:features:5.0.0-SNAPSHOT:compile"
      - dependency-name: "org.openhab.ui.features:org.openhab.ui.features:xml:features:5.0.0-SNAPSHOT:provided"
      - dependency-name: "org.openhab.ui.features:org.openhab.ui.features:xml:features:5.0.0-SNAPSHOT:runtime"
      - dependency-name: "org.opentest4j:opentest4j"
      - dependency-name: "org.ops4j.base:ops4j-base-lang"
      - dependency-name: "org.ops4j.base:ops4j-base-util-collections"
      - dependency-name: "org.ops4j.base:ops4j-base-util-property"
      - dependency-name: "org.ops4j.pax.logging:pax-logging-api"
      - dependency-name: "org.ops4j.pax.logging:pax-logging-log4j2"
      - dependency-name: "org.ops4j.pax.logging:pax-logging-log4j2-maven-plugin"
      - dependency-name: "org.ops4j.pax.logging:pax-logging-logback"
      - dependency-name: "org.ops4j.pax.swissbox:pax-swissbox-property"
      - dependency-name: "org.ops4j.pax.url:pax-url-aether"
      - dependency-name: "org.osgi:org.osgi.namespace.implementation"
      - dependency-name: "org.osgi:org.osgi.namespace.service"
      - dependency-name: "org.osgi:org.osgi.service.cm"
      - dependency-name: "org.osgi:org.osgi.service.jaxrs"
      - dependency-name: "org.osgi:org.osgi.util.function"
      - dependency-name: "org.osgi:org.osgi.util.promise"
      - dependency-name: "org.osgi:osgi.annotation"
      - dependency-name: "org.osgi:osgi.cmpn"
      - dependency-name: "org.osgi:osgi.core"
      - dependency-name: "org.ow2.asm:asm"
      - dependency-name: "org.slf4j:jcl-over-slf4j"
      - dependency-name: "org.slf4j:slf4j-api"
      - dependency-name: "org.slf4j:slf4j-reload4j"
      - dependency-name: "xml-apis:xml-apis"
