#!/bin/sh

set -e

[ -f /etc/default/openhab2 ] && . /etc/default/openhab2

startOpenHAB() {
	if [ -x /bin/systemctl ] ; then
		/bin/systemctl daemon-reload
		/bin/systemctl start openhab2.service
	elif [ -x "/etc/init.d/openhab2" ]; then
		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
			invoke-rc.d openhab2 start || true
		else
			/etc/init.d/openhab2 start || true
		fi
	fi
}

case "$1" in
	configure)
	# if $2 is set, this is an upgrade
		if [ -n $2 ] ; then
			startOpenHAB
	# this is a fresh installation
		else
			if [ -x /bin/systemctl ] ; then
				echo "### NOT starting on installation, please execute the following statements to configure openHAB to start automatically using systemd"
				echo " sudo /bin/systemctl daemon-reload"
				echo " sudo /bin/systemctl enable openhab2.service"
				echo "### You can start openhab2 by executing"
				echo " sudo /bin/systemctl start openhab2.service"
			elif [ -x /usr/sbin/update-rc.d ] ; then
				echo "### NOT starting openhab2 by default on bootup, please execute"
				echo " sudo update-rc.d openhab2 defaults"
				echo "### In order to start openhab2, execute"
				echo " sudo /etc/init.d/openhab2 start"
			fi
		fi
		;;
esac

exit 0
