#!/bin/sh

set -e

case "$1" in
	install)
		OH_USER=openhab
		OH_GROUP=openhab
		if [ x"${USER_AND_GROUP}" != x ]; then
			OH_USER=`echo ${USER_AND_GROUP} | cut -d ":" -f 1`
			OH_GROUP=`echo ${USER_AND_GROUP} | cut -d ":" -f 2`
		fi
		if ! getent group "$OH_GROUP" > /dev/null 2>&1 ; then
			addgroup --system "$OH_GROUP" --quiet
		fi
		if ! getent passwd "$OH_USER" > /dev/null 2>&1 ; then
			adduser --quiet --system --ingroup "$OH_GROUP" --no-create-home \
			--disabled-password --shell /bin/false \
			--gecos "openhab2 runtime user" --home /var/lib/openhab2 "$OH_USER"
		fi
		;;
esac

exit 0
