#!/bin/sh

set -e

[ -f /etc/default/openhab2 ] && . /etc/default/openhab2

stopOpenHAB() {
	if [ -x /bin/systemctl ] ; then
		/bin/systemctl --no-reload stop openhab2.service > /dev/null 2>&1 || :
	elif [ -x "/etc/init.d/openhab2" ]; then
		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
			invoke-rc.d openhab2 stop
		else
			/etc/init.d/openhab2 stop
		fi
		# waiting for the openhab2 process stop (max 10 seconds), otherwise the removal of the user will fail.
		# workaround /etc/init.d/openhab2 stop the service needs some time to stop
		sleep 5
	fi
}

case "$1" in
	upgrade)
		stopOpenHAB
		;;
	remove|deconfigure)
		stopOpenHAB
		;;
	failed-upgrade)
		;;
esac

exit 0
