#! /bin/sh
### BEGIN INIT INFO
# Provides:          openhab2
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: openHAB2 server
# Description:       Start / Stop openHAB2 server
### END INIT INFO

# Author: openHAB <openhab@openhab.org>
#


PATH=/sbin:/usr/sbin:/bin:/usr/bin
OPENHAB_INST_DIR="/usr/share/openhab2"

DESC="openHAB2 server"
NAME=openhab2
JAVA="/usr/bin/java"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
SETOWNER=yes

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

# Read configuration variable file if it is present
[ -r /etc/default/openhab2 ] && . /etc/default/openhab2

OPENHAB_CONF_DIR="/etc/openhab2"
OPENHAB_DIR="/usr/share/openhab2"
OPENHAB_HOME_DIR="/var/lib/openhab2"
OPENHAB_USER_DATA_DIR="${OPENHAB_HOME_DIR}"

if [ -z "$USER_AND_GROUP" ]; then
        USER_AND_GROUP="openhab:openhab"
fi

if [ x"${OPENHAB_JAVA}" != x ]; then
    JAVA="${OPENHAB_JAVA}"
fi

if [ -n ${EXTRA_JAVA_OPTS} ]; then
    export EXTRA_JAVA_OPTS
fi

if [ ! -x "${JAVA}" ]; then
    log_failure_msg "no java executable found at ${JAVA}"
    exit 2
fi

USER=`echo ${USER_AND_GROUP} | cut -d ":" -f 1`
GROUP=`echo ${USER_AND_GROUP} | cut -d ":" -f 2`

#Check whether the specified user exists
if ! getent passwd "${USER}" > /dev/null 2>&1; then
    log_failure_msg "runtime user doesn't exists"
    exit 2
fi

#Check whether the specified group exists
if ! getent group "${GROUP}" > /dev/null 2>&1; then
    log_failure_msg "runtime group doesn't exists"
    exit 2
fi

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

case "$1" in
  start)
        log_daemon_msg "Starting $DESC" "$NAME"
        #${OPENHAB_INST_DIR}/bin/setpermissions.sh > /dev/null
        if start-stop-daemon --start --quiet --pidfile $PIDFILE -c "${USER_AND_GROUP}" --umask 002 --background --make-pidfile --chdir ${OPENHAB_DIR} \
                --oknodo --exec /usr/share/openhab2/runtime/karaf/bin/start
        then
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
  stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        if /usr/share/openhab2/runtime/karaf/bin/stop
        then
            rm -f $PIDFILE
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
  status)
        /usr/share/openhab2/runtime/karaf/bin/status
        ;;
  restart|force-reload)
        log_daemon_msg "Restarting $DESC" "$NAME"
        if /usr/share/openhab2/runtime/karaf/bin/stop
        then
            if /usr/share/openhab2/runtime/karaf/bin/start
            then
                log_end_msg 0
            else
               log_end_msg 1
            fi
        else
            log_end_msg 1
        fi
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
        exit 3
        ;;
esac
