#!/bin/sh

# store here all configuration options for openhab snap
SNAP_NAME="openhab"

# read configured settings first
SETTINGS_FILE="$SNAP_COMMON/openhab_settings.sh"
[ -f $SETTINGS_FILE ] && . $SETTINGS_FILE

# list of supported keys
keys="OPENHAB_HTTP_PORT OPENHAB_HTTPS_PORT"

# default values
DESCRIPTION_OPENHAB_HTTP_PORT="http port openhab is exposed on, atter change restart service"
DEFAULT_OPENHAB_HTTP_PORT="8080"
KEY_OPENHAB_HTTP_PORT="http-port"

DESCRIPTION_OPENHAB_HTTPS_PORT="https port openhab is exposed on, atter change restart service"
DEFAULT_OPENHAB_HTTPS_PORT="8443"
KEY_OPENHAB_HTTPS_PORT="https-port"
