#!/bin/bash

source $SNAP/bin/config &>/dev/null

echo -e "openHAB: open source automation software for your home\n"
echo -e "Make sure you have connected all interfaces, check more by calling $ snap interfaces"
echo -e "Basic set can connected using helper script $ /snap/$SNAP_NAME/current/bin/connect-interfaces\n"
# parse config file for supported settings keys
echo -e "openHAB supports settings keys"
echo -e "values can be changed by calling\n$ snap set $SNAP_NAME <key name>='<key value>'"
echo -e "list of supported keys:"
for key in ${keys[@]}
do
    default_value="DEFAULT_$key"
    description="DESCRIPTION_$key"
    snappy_key="KEY_$key"
    echo -e "\t${!snappy_key}:   ${!description}"
    if [ "x" == "x${!key}" ]; then
        echo -e "\t\tNo value set, using default value: '${!default_value}'"
    else
        echo -e "\t\tCurrent value set to: '${!key}', (default value: '${!default_value}')"
    fi
done
echo -e "\nFor some changes to take effect openHAB server needs to be restarted"
echo -e "to restart openHAB server: $ sudo systemctl restart snap.$SNAP_NAME.openhab"
echo -e "\nTo access openHAB server console use $ $SNAP_NAME.client"
